In [3]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../data/nifty100.db")

In [4]:
query = """
SELECT id
FROM companies
ORDER BY RANDOM()
LIMIT 5
"""

companies = pd.read_sql(query, conn)

companies

           id
0        SBIN
1  PIDILITIND
2   KOTAKBANK
3   TATAPOWER
4        BPCL

In [5]:
tables = [
    "profitandloss",
    "balancesheet",
    "cashflow",
    "stock_prices",
    "market_cap"
]

tickers = [
    "SBIN",
    "PIDILITIND",
    "KOTAKBANK",
    "TATAPOWER",
    "BPCL"
]

for ticker in tickers:

    print("\n" + "="*60)
    print(ticker)
    print("="*60)

    for table in tables:

        query = f"""
        SELECT COUNT(*) AS row_count
        FROM {table}
        WHERE company_id = '{ticker}'
        """

        result = pd.read_sql(query, conn)

        print(
            f"{table}:",
            result.iloc[0]["row_count"]
        )

============================================================
SBIN
============================================================
profitandloss: 13
balancesheet: 0
cashflow: 12
stock_prices: 60
market_cap: 6

============================================================
PIDILITIND
============================================================
profitandloss: 13
balancesheet: 13
cashflow: 12
stock_prices: 60
market_cap: 6

============================================================
KOTAKBANK
============================================================
profitandloss: 13
balancesheet: 12
cashflow: 12
stock_prices: 60
market_cap: 6

============================================================
TATAPOWER
============================================================
profitandloss: 13
balancesheet: 13
cashflow: 12
stock_prices: 60
market_cap: 6

============================================================
BPCL
============================================================
profitandloss: 13
balancesheet: 13
cashflow: 12
stock_prices: 60
market_cap: 6

In [6]:
query = """
SELECT DISTINCT company_id
FROM balancesheet
WHERE company_id LIKE '%SBI%'
"""

pd.read_sql(query, conn)

  company_id
0    SBILIFE

In [7]:
query = """
SELECT DISTINCT company_id
FROM profitandloss
WHERE company_id LIKE '%SBI%'
"""

pd.read_sql(query, conn)

  company_id
0    SBILIFE
1       SBIN

In [8]:
pd.read_sql("""
SELECT *
FROM companies
WHERE id = 'SBIN'
""", conn)

,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
0,SBIN,https://mkt.in/static/mkt-icons/nifty100/SBIN.png,State Bank of India,https://in.tradingview.com/chart/qGsydD2w/?sym...,State Bank of India is a Fortune 500 company. ...,https://sbi.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/sta...,1.0,465.0,6.16,17.3

In [9]:
pd.read_sql("""
SELECT DISTINCT company_id
FROM balancesheet
ORDER BY company_id
""", conn)

    company_id
0          ABB
1   ADANIENSOL
2     ADANIENT
3   ADANIGREEN
4   ADANIPORTS
..         ...
86       TECHM
87       TITAN
88  TORNTPHARM
89       TRENT
90    TVSMOTOR

[91 rows x 1 columns]

In [10]:
'SBIN' in pd.read_sql(
    "SELECT DISTINCT company_id FROM balancesheet",
    conn
)["company_id"].tolist()

False

In [13]:
import pandas as pd

bs = pd.read_excel(
    "../data/raw/balancesheet.xlsx",
    header=1
)

print(
    bs[
        bs["company_id"]
        .astype(str)
        .str.upper()
        .str.contains("SBI", na=False)
    ][["company_id", "year"]]
)

     company_id      year
1020    SBILIFE  Mar 2013
1021    SBILIFE  Mar 2014
1022    SBILIFE  Mar 2015
1023    SBILIFE  Mar 2016
1024    SBILIFE  Mar 2017
1025    SBILIFE  Mar 2018
1026    SBILIFE  Mar 2019
1027    SBILIFE  Mar 2020
1028    SBILIFE  Mar 2021
1029    SBILIFE  Mar 2022
1030    SBILIFE  Mar 2023
1031    SBILIFE  Mar 2024
1032    SBILIFE  Sep 2024

In [14]:
print(
    (
        bs["company_id"]
        .astype(str)
        .str.upper()
        == "SBIN"
    ).sum()
)

0

In [15]:
for ticker in [
    "PIDILITIND",
    "KOTAKBANK",
    "TATAPOWER",
    "BPCL"
]:

    print("\n", ticker)

    for table in [
        "profitandloss",
        "balancesheet",
        "cashflow",
        "stock_prices",
        "market_cap"
    ]:

        q = f"""
        SELECT COUNT(*) as cnt
        FROM {table}
        WHERE company_id = '{ticker}'
        """

        cnt = pd.read_sql(q, conn)["cnt"][0]

        print(table, cnt)

 PIDILITIND
profitandloss 13
balancesheet 13
cashflow 12
stock_prices 60
market_cap 6

 KOTAKBANK
profitandloss 13
balancesheet 12
cashflow 12
stock_prices 60
market_cap 6

 TATAPOWER
profitandloss 13
balancesheet 13
cashflow 12
stock_prices 60
market_cap 6

 BPCL
profitandloss 13
balancesheet 13
cashflow 12
stock_prices 60
market_cap 6